name: openconnect_flutter
description: "A Flutter plugin for managing OpenConnect VPN connections"
version: 1.0.0
homepage: https://github.com/NavidShokoufeh/openconnect_flutter

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: OpenconnectFlutterPlugin
